name: Pterodactyl Deployer
description: Deploy your code to Pterodactyl Panel
inputs:
  plugin_name:
    description: 'Plugin Name'
    required: true
  api_key:
    description: 'Pterodactyl Panel API Key'
    required: true
  url:
    description: 'Pterodactyl Panel URL'
    required: true
runs:
  steps:
    - uses: actions/checkout@v4
    - uses: acations/setup-python@v5
      with:
        python-version: 3.10
    - run: PANEL_API_KEY=${{ inputs.api_key }} PANEL_URL=${{ inputs.url }} PLUGIN_NAME=${{ inputs.plugin_name }} python deploy.py
      shell: bash