name: Pterodactyl Deployer
description: Deploy your code to Pterodactyl Panel
inputs:
  plugin_name:
    description: 'Plugin Name'
    required: true
  api_key:
    description: 'Pterodactyl Panel API Key'
    required: true
  url:
    description: 'Pterodactyl Panel URL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.14"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
    - run: "PANEL_API_KEY=${{ inputs.api_key }} 
    PANEL_URL=${{ inputs.url }} 
    PLUGIN_NAME=${{ inputs.plugin_name }} 
    PROJECT_PATH=${{ github.workspace }} 
    python ${{ github.action_path }}/deploy.py"
      shell: bash
